### ISSUE TITLE
Ignore dist directories in source control, build on prepublish instead

### ISSUE THREAD

**Issue by abdelrahman-elkady** [RobustaStudio/robust-tools#13]
I was checking this repo, and found that the transpiled code is checked out in source, are you sure you are including [`dist`](https://github.com/RobustaStudio/robust-tools/tree/master/packages/fader/dist) on purpose ?

I guess you can do the transpilation on [`prepublish`](https://docs.npmjs.com/misc/scripts) if you want to ship this to npm

**Comment by ahmadalfy** [comment]
Thanks, I am still exploring what needs to be done because I've never published anything to NPM before. I will check that and probably follow your suggestion, thank you

**Comment by abdelrahman-elkady** [comment]
Great, updating the issue title then

**Comment by ahmadalfy** [comment]
@abdelrahman-elkady can you help me do that?

**Comment by abdelrahman-elkady** [comment]
Yeah, sure

As far as I can see, this is a mono-repo, I never published packages using `lerna` before, but [as I can see](https://github.com/lerna/lerna/issues/1275), they just call `npm publish` on each package, thus, triggering the same lifecycle scripts

so, in the packages you want to publish, just add a `prepublishOnly` script for building and ignore `dist` 

You can check #50 and start from there to test if your pipeline works fine with this change
